[project]
name = "viddl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlalchemy>=2.0.40",
    "yt-dlp[curl-cffi,default]>=2025.3.27",
]
